### ISSUE TITLE
How does it work on the video?

### ISSUE THREAD

**Issue by czprincefly** [amanchadha/iPerceive#1]
Hello, Aman Chadha. Thanks for your code! I see the work's name is Applying Common-Sense Reasoning to Video, but I just see it work on the images, how does it work on the video?

**Comment by amanchadha** [comment]
Hey!

Indeed, the proposed common-sense generation framework works elegantly on videos - we've applied the technique to the domains of video captioning and question-answering and further the state-of-the-art on both these domains with our common-sense generation technique.

I'd like to point you to the following reading material so you can get some more insight on how we handle videos effectively:

- ["I've heard that tasks involving video need serious compute horse-power and time. Is common-sense generation for videos computationally expensive?"](https://github.com/amanchadha/iPerceive#ive-heard-that-tasks-involving-video-need-serious-compute-horse-power-and-time-is-common-sense-generation-for-videos-computationally-expensive)
- [Project Report --Section 3 and 4 (soon to be published as a paper)](https://amanchadha.com/projects/ai/cnn/Chadha_iPerceive_ProjectReport.pdf)

Hope this helps!
