### ISSUE TITLE
May I ask the location of the csfeatures file？

### ISSUE THREAD

**Issue by BNU-Wu** [amanchadha/iPerceive#2]
Hello, @amanchadha ,thank you for your excellent work. I want to implement your iPerceiveDVC, but found that a csfeatures file is needed. You gave the data link, but it contains multiple compressed packages. Unfortunately, my download resources are limited. May I ask which compressed package your cs file is in? Thank you very much and look forward to your reply.

**Comment by amanchadha** [comment]
Hey!

Thanks for the kind words :)

You can just use the [pre-trained model](https://drive.google.com/drive/folders/1y44pwGVVzRTr11tDKGnNEabOrif01QX4?usp=sharing) and apply it to the problem at hand. iPerceive will automatically extract the common-sense features ("csfeatures") at runtime.

**Comment by BNU-Wu** [comment]
Oh, thank you!
