### ISSUE TITLE
Multi-lingual audio

### ISSUE THREAD

**Issue by amil-rp-work** [amanchadha/iPerceive#3]
Hey @amanchadha 
Thanks for open-sourcing your work!!!
Since the model uses audio, visual, and speech features, how well does it work for multilingual audio? 
Also is there a possibility to use a non-audio based image captioning set?

**Comment by amanchadha** [comment]
Hi @amil-rp-work ! Thanks for your interest in iPerceive! Indeed, the model is scalable to as many modalities as you'd like so it should be possible to have multilingual audio features (have each audio language track generate its own feature set and feed it into its own Transformer arch). Having a non-audio based image captioning set should also be similarly possible.

**Comment by amil-rp-work** [comment]
Thanks for the inputs @amanchadha!
I had two questions following this 
- If I have a dataset of videos with captions(English language) and Audio(not limited to a single language), I believe I should just simply follow the instructions to train, right?
- Is it possible for me to leverage some of your pre-trained models for Captioning on my own wild videos?

**Comment by amanchadha** [comment]
> If I have a dataset of videos with captions(English language) and Audio(not limited to a single language), I believe I should just simply follow the instructions in README.md to train, right?

Yes!

> Is it possible for me to leverage some of your pre-trained models for Captioning on my own wild videos?

Absolutely!

> Are there pre-trained model available for no audio captioning?

Yes - that's how we handle videos with no audio modality. Use the same pre-trained model to accomplish this.

**Comment by amil-rp-work** [comment]
Thanks for clearing my doubts on the training pipeline, will begin it right away !!!

As for leveraging your pre-trained models, I can currently only see using it as a feature extractor or training in the `README.md`. Could you provide a small set of instructions to get me started on using your pre-trained models for inferencing on wild new videos?

**Comment by amanchadha** [comment]
Sure @amil-rp-work , check out the "Using our pre-trained iPerceive model on COCO" section here: https://github.com/amanchadha/iPerceive#feature-extraction-aka-inferencetesting-since-this-is-a-self-supervised-setting
