### ISSUE TITLE
iPerceive VideoQA

### ISSUE THREAD

**Issue by engindeniz** [amanchadha/iPerceive#4]
Regarding iPerceive VideoQA, could you share your trained model and csfeatures? According to your drive share links,  you shared the baseline papers' model and their pre-trained features.

Did you use the dense captions produced by iPerceive DVC for VideoQA? In the paper, it seems that you used these captions, but I couldn't find them in the codes.

Also, you create three different conda environments for the overall project. How do separate modules work together?

**Comment by amanchadha** [comment]
Hi @engindeniz ,

> Regarding iPerceive VideoQA, could you share your trained model and csfeatures? According to your drive share links, you shared the baseline papers' model and their pre-trained features.

I do not have the csfeatures handy, but the pre-trained model is now available here: https://drive.google.com/file/d/1V4guUifhjk69KWaiH0ss1XCnmUsp1FMR/view?usp=sharing

> Did you use the dense captions produced by iPerceive DVC for VideoQA? In the paper, it seems that you used these captions, but I couldn't find them in the codes.

Yes, we did. But they haven't been uploaded. 

> Also, you create three different conda environments for the overall project. How do separate modules work together?

The environments are indeed independent.
iPerceive generates CS Features for iPerceive DVC and saves them offline.
iPerceive DVC does its processing and delivers its output.
iPerceive DVC's output feeds iPerceive VideoQA.
