### ISSUE TITLE
Details in the ablation parts

### ISSUE THREAD

**Issue by doc-doc** [amanchadha/iPerceive#6]
Hi, can you share some details in the ablation parts? For common-sense reasoning, did you remove the whole reasoning module? or you still kept the naive RoI feature but ignored the VC feature?

**Comment by amanchadha** [comment]
Hi @doc-doc , we removed the whole reasoning module for ablation experiments.

**Comment by doc-doc** [comment]
Thank you for the prompt reply, but shouldn't it makes more sense to keep the RoI feature to study commonsense?

**Comment by doc-doc** [comment]
Thank you for the prompt reply, but shouldn't it make more sense to keep the RoI feature to study commonsense?

**Comment by amanchadha** [comment]
The RoI features are utilized only for commonsense development. The individual DVC and VideoQA models develop and utilize their own features (which do *not* intersect with the RoI features that are used for commonsense).

**Comment by doc-doc** [comment]
Yes, I know.  I was interested to know the results that utilize RoI features but without de-confounder training. Will you do such experiments? I think this work is interesting and would shed light on causal reasoning between actions/events in videos.

**Comment by amanchadha** [comment]
Sounds like a good exploratory exercise to me. I do not have any plans to carry out more experiments at this stage. I do see the value in exploring this further. If you are looking to take upon the task, I can support you.
