### ISSUE TITLE
Link of VC-R-CNN is missing in the install.sh file

### ISSUE THREAD

**Issue by siyamsajeebkhan** [amanchadha/iPerceive#8]
Hi, 
While running the install.sh file from the iPrceive directory, I found out the cloning link of the git repo of the VC-R-CNN is missing. I think, the following line should be added to the install.sh file after line 45:

After the comment `# install VC`, this should be added:
`git clone https://github.com/Wangt-CN/VC-R-CNN.git`

**Comment by amanchadha** [comment]
I just fixed the issue in `install.sh`. You do not need to clone VC-R-CNN. Everything you need to run iPerceive is self-contained in the iPerceive git repo. Thanks for highlighting this!

**Comment by siyamsajeebkhan** [comment]
Thanks for updating the install.sh file. I am having a few issues while trying to set up everything. When I am executing the following command from the apex folder I am getting the following error:

command: `python3 setup.py install --cuda_ext --cpp_ext` [inside the apex folder]
Error: 
> # RuntimeError: Cuda extensions are being compiled with a version of Cuda that does not match the version used to compile >Pytorch binaries.  Pytorch binaries were compiled with Cuda 10.0.130. In some cases, a minor-version mismatch will not cause >later errors:  https://github.com/NVIDIA/apex/pull/323#discussion_r287021798.  You can try commenting out this check (at your >own risk).

I am assuming I am getting this due to the mismatch in the version of cuda installed using `sudo sh cuda_10.2.89_440.33.01_linux.run` and the version of cuda installed with pytorch. I tried doing `export CUDA_HOME=/usr/local/cuda-10.2/` but the issue wasn't resolved. 

What am I missing or doing wrong? Could you please rectify? 

Thanks again for your very prompt replies!

**Comment by siyamsajeebkhan** [comment]
Okay, at last this combination worked for me. I could setup the environment using the following settings:

Pytorch: 1.4.0
torchvision: 0.5.0
cuda: 10.1

And, I modified the `install.sh` file as following:
`#!/bin/bash

# # this installs the right pip and dependencies for the fresh python

# CUDA Toolkit 10.2 Download
# wget http://developer.download.nvidia.com/compute/cuda/10.2/Prod/local_installers/cuda_10.2.89_440.33.01_linux.run
# sudo sh cuda_10.2.89_440.33.01_linux.run

#conda install python=3.7
# maskrcnn_benchmark and coco api dependencies
# install latest versions in your global environment
pip3 install ninja yacs cython matplotlib tqdm opencv-python h5py lmdb

# for maskrcnn
conda install tensorflow scikit-image
conda remove imgaug
conda install -c conda-forge geos
conda install -c conda-forge shapely
conda config --add channels conda-forge
conda install imgaug

# install specific versions in your conda environment
# follow PyTorch installation in https://pytorch.org/get-started/locally/
# we give the instructions for CUDA 10.0
# conda install -c pytorch==1.4.0 pytorch-nightly torchvision==0.5.0 cudatoolkit=10.0
conda install -c pytorch pytorch==1.4.0 torchvision==0.5.0

# install pytorch
#conda install -c pytorch pytorch-nightly=1.0.0 torchvision=0.2.2
pip3 install 'pillow<7.0.0'

# install pycocotools
cd ..
git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
python3 setup.py build_ext install

# install apex
cd ..
cd ..
git clone https://github.com/NVIDIA/apex.git
cd apex
python3 setup.py install --cuda_ext --cpp_ext
cd ..

# install iPerceive
cd iPerceive
python3 setup.py build develop
`
